name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
#        java-version: '21-distroless'
        java-version: '21'
        distribution: 'temurin'
#        distribution: 'microsoft'

    - name: Build container with Maven
      run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=hecklerm/catwd-demo:cnbjvm

#    - name: Build with Maven
#      run: mvn clean package -DskipTests
#
#    - name: Build Docker image
#      run: docker build -t hecklerm/catwd-demo:distroless .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push hecklerm/catwd-demo:cnbjvm
